---
- name: Example playbook to send results to Slack
  hosts: localhost
  tasks:
    - name: Run some task
      command: echo "Hello, World!"
      register: result

    - name: Send result to Slack
      slack:
        token: "https://hooks.slack.com/services/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"
        msg: "Playbook finished with result: {{ result.stdout }}"
        channel: "#최적화-프로젝트"
