---
- name: Example playbook to send results to Slack
  hosts: localhost
  tasks:
    - name: Run some task
      command: echo "Hello, World!"
      register: result

    - name: Send result to Slack
      slack:
        token: "https://hooks.slack.com/services/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"
        msg: "Playbook finished with result: {{ result.stdout }}"
        channel: "#토이프로젝트"
