---
- name: Send stdout to Slack
  hosts: localhost
  gather_facts: no
  vars:
    slack_webhook_url: "https://hooks.slack.com/services/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"  # Slack Webhook URL
  tasks:
    - name: Run a command and register the output
      command: echo "This is a test message from Ansible"
      register: command_output

    - name: Send stdout to Slack
      uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "text": "Command Output: {{ command_output.stdout }}"
          }
        body_format: json
      delegate_to: localhost
