---
- name: Shutdown port 1/1 on Cisco Nexus switch
  hosts: cisco
  gather_facts: no
  tasks:
    - name: Configure the interface to no shutdown
      cisco.nxos.nxos_interfaces:
        config:
          - name: Ethernet1/1
            enabled: true
          - name: Ethernet1/2
            enabled: true
        state: merged

    - name: Input Check CLI
      cisco.nxos.nxos_command:
        commands:
          - show interface status
      register: config
      
    - name: Print config
      debug:
        var: config
