---
- name: Shutdown port 1/1 on Cisco Nexus switch
  hosts: cisco
  gather_facts: no
  tasks:
    - name: Configure the interface to shutdown
      cisco.nxos.nxos_interface:
        name: Ethernet1/1
        admin_state: down
      register: result
