---
- name: Shutdown port 1/1 on Cisco Nexus switch
  hosts: cisco
  gather_facts: no
  tasks:
    - name: Configure the interface to shutdown
      cisco.nxos.nxos_config:
        lines:
          - no shutdown
        parents: interface Ethernet1/1

    - name: Print config
      debug:
        var: config
