---
- name: DR_excute
  hosts: juniper
  gather_facts: no
  tasks:
    - name: Disable_interface
      juniper.device.config:
        load: "set"
        lines:
          - "set interfaces ge-0/0/0 disable"
          - "set interfaces ge-0/0/3 disable"
          - "set interfaces ge-0/0/4 disable"
#---
- name: Shutdown port 1/1 on Cisco Nexus switch
  hosts: cisco
  gather_facts: no
  tasks:
    - name: Configure the interface to shutdown
      cisco.nxos.nxos_interfaces:
        config:
          - name: Ethernet1/1
            description: Configured by Ansible
            enabled: false
          - name: Ethernet1/2
            description: Configured by Ansible Network
            enabled: false
    state: merged

    - name: Input Check CLI
      cisco.nxos.nxos_command:
        commands:
          - show interface status
      register: config

    - name: Print config
      debug:
        var: config
