---
- name: Coupang_DR_Juniper
  hosts: juniper
  gather_facts: no
  tasks:
    - name: shutdown_juniper
      include: CP/dr_excute.yml

- name: Coupang_DR_Cisco
  hosts: cisco
  gather_facts: no
  tasks:
    - name: shutdown_cisco
      include: CP/dr_excute_nxos.yml
